
modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="No licensed"

[[mods]] #mandatory
modId="icnext" #mandatory
version="${file.jarVersion}" #mandatory
displayName="IndustrialCraft-Next" #mandatory
logoFile="examplemod.png" #optional
credits="" #optional
authors="LegenLee" #optional
description='''
From old thing, Create next generation.
'''

[[dependencies.icnext]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.icnext]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
